### ISSUE TITLE
ExPlat: Main Issue

### ISSUE THREAD

**Issue by RenanLukas** [Automattic/Automattic-Tracks-Android#116]
Original issue created by @renanferrari in [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android/issues/14089)
___
This issue centralizes all tasks and potential improvements to the ExPlat implementation on WPAndroid.

### Tasks
- [x] Initial A/A experiment implementation. (PR: https://github.com/wordpress-mobile/WordPress-Android/pull/13960)
- [x] Initial A/B experiment implementation. (PR: https://github.com/wordpress-mobile/WordPress-Android/pull/14286)
- [ ] Add support for logged-out experiments.
- [x] Add functionality to manage active experiments. (PR: https://github.com/wordpress-mobile/WordPress-Android/pull/14559)
- [ ] Add UI to list active experiments (for internal testing only).
- [ ] Add functionality to manually edit assignments of active experiments (for internal testing only).
- [ ] Add support for other loading strategies (experiments that require loading screens, for example).
- [ ] Consider not fetching assignments if data collection is turned off.
- [x] Extract implementation to a shared library (which one is yet TBD). (https://github.com/Automattic/Automattic-Tracks-Android/pull/114)
- [ ] `:experimentation` module depends on FluxC because of the classes `ExperimentStore` and `ExperimentRestClient`. We should move these classes to `:experimentation` module to stop depending on FluxC.
- [ ] refactor `ExPlat` class [so we don't have to use `Lazy` to avoid circular dependency](https://github.com/woocommerce/woocommerce-android/pull/6055/files#diff-ffb3cac4e8e2367390ceae7729e4582e3d629ffb91ecc5394805fe90e7a44067R28) in the `Set<Experiment>` parameter. We should consider splitting the `ExPlat` class.

### Notes
- I'm going to update the tasks with links for the specific issues and PRs once they're up.
